export const expressionLabels: Record<string, string> = {
  admiration: "Admiration",
  adoration: "Adoration",
  aestheticAppreciation: "Aesthetic Appreciation",
  amusement: "Amusement",
  anger: "Anger",
  annoyance: "Annoyance",
  anxiety: "Anxiety",
  awe: "Awe",
  awkwardness: "Awkwardness",
  boredom: "Boredom",
  calmness: "Calmness",
  concentration: "Concentration",
  contemplation: "Contemplation",
  confusion: "Confusion",
  contempt: "Contempt",
  contentment: "Contentment",
  craving: "Craving",
  determination: "Determination",
  disappointment: "Disappointment",
  disapproval: "Disapproval",
  disgust: "Disgust",
  distress: "Distress",
  doubt: "Doubt",
  ecstasy: "Ecstasy",
  embarrassment: "Embarrassment",
  empathicPain: "Empathic Pain",
  enthusiasm: "Enthusiasm",
  entrancement: "Entrancement",
  envy: "Envy",
  excitement: "Excitement",
  fear: "Fear",
  gratitude: "Gratitude",
  guilt: "Guilt",
  horror: "Horror",
  interest: "Interest",
  joy: "Joy",
  love: "Love",
  neutral: "Neutral",
  nostalgia: "Nostalgia",
  pain: "Pain",
  pride: "Pride",
  realization: "Realization",
  relief: "Relief",
  romance: "Romance",
  sadness: "Sadness",
  sarcasm: "Sarcasm",
  satisfaction: "Satisfaction",
  sexualDesire: "Sexual Desire",
  shame: "Shame",
  surprise: "Surprise",
  surpriseNegative: "Surprise (Negative)",
  surprisePositive: "Surprise (Positive)",
  sympathy: "Sympathy",
  tiredness: "Tiredness",
  triumph: "Triumph",
};
